"""add image table

Revision ID: 9bd4fc122de1
Revises: 8a6d7c4e2f10
Create Date: 2026-09-29 08:16:34.358712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9bd4fc122de1'
down_revision: Union[str, Sequence[str], None] = '8a6d7c4e2f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_inv_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_inv_images')
    # ### end Alembic commands ###
